/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Audit (
  id: Option[String],
  createAt: Option[Int],
  userId: Option[String],
  action: Option[String],
  extraInfo: Option[String],
  ipAddress: Option[String],
  sessionId: Option[String]
) extends ApiModel


