/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body (
  email: String,
  username: String,
  firstName: Option[String],
  lastName: Option[String],
  nickname: Option[String],
  password: String,
  locale: Option[String],
  props: Option[Any],
  notifyProps: Option[UserNotifyProps]
) extends ApiModel


