/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body14 (
  /* The service the user currently uses to login */
  currentService: String,
  /* The service the user will use to login */
  newService: String,
  /* The email of the user */
  email: Option[String],
  /* The password used with the current service */
  password: Option[String],
  /* The MFA code of the current service */
  mfaCode: Option[String],
  /* The LDAP/AD id of the user */
  ldapId: Option[String]
) extends ApiModel


