/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body16 (
  /* Unique handler for a team, will be present in the team URL */
  name: String,
  /* Non-unique UI name for the team */
  displayName: String,
  /* `'O'` for open, `'I'` for invite only */
  `type`: String
) extends ApiModel


