/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body1 (
  /* The term to match against username, full name, nickname and email */
  term: String,
  /* If provided, only search users on this team */
  teamId: Option[String],
  /* If provided, only search users not on this team */
  notInTeamId: Option[String],
  /* If provided, only search users in this channel */
  inChannelId: Option[String],
  /* If provided, only search users not in this channel. Must specifiy `team_id` when using this option */
  notInChannelId: Option[String],
  /* When `true`, include deactivated users in the results */
  allowInactive: Option[Boolean],
  /* Set this to `true` if you would like to search for users that are not on a team. This option takes precendence over `team_id`, `in_channel_id`, and `not_in_channel_id`. */
  withoutTeam: Option[Boolean]
) extends ApiModel


