/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body32 (
  /* The ID of a public channel or private group that receives the webhook payloads. */
  channelId: String,
  /* The display name for this incoming webhook */
  displayName: Option[String],
  /* The description for this incoming webhook */
  description: Option[String],
  /* The username this incoming webhook will post as. */
  username: Option[String],
  /* The profile picture this incoming webhook will use when posting. */
  iconUrl: Option[String]
) extends ApiModel


