/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body29 (
  /* The search terms as inputed by the user. */
  terms: String,
  /* Set to true if an Or search should be performed vs an And search. */
  isOrSearch: Boolean
) extends ApiModel


