/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body21 (
  /* The team ID of the team to create the channel on */
  teamId: String,
  /* The unique handle for the channel, will be present in the channel URL */
  name: String,
  /* The non-unique UI name for the channel */
  displayName: String,
  /* A short description of the purpose of the channel */
  purpose: Option[String],
  /* Markdown-formatted text to display in the header of the channel */
  header: Option[String],
  /* 'O' for a public channel, 'P' for a private channel */
  `type`: String
) extends ApiModel


