/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body27 (
  /* Set to `true` to pin the post to the channel it is in */
  isPinned: Option[Boolean],
  /* The message text of the post */
  message: Option[String],
  /* The list of files attached to this post */
  fileIds: Option[Seq[Any]],
  /* Set to `true` if the post has reactions to it */
  hasReactions: Option[Boolean],
  /* A general JSON property bag to attach to the post */
  props: Option[String]
) extends ApiModel


