/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body39 (
  /* The id of the client application */
  id: String,
  /* The name of the client application */
  name: String,
  /* A short description of the application */
  description: String,
  /* A URL to an icon to display with the application */
  iconUrl: Option[String],
  /* A list of callback URLs for the appliation */
  callbackUrls: Seq[String],
  /* A link to the website of the application */
  homepage: String,
  /* Set this to `true` to skip asking users for permission. It will be set to false if value is not provided. */
  isTrusted: Option[Boolean]
) extends ApiModel


