/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body30 (
  /* The type of job to create */
  `type`: String,
  /* An object containing any additional data required for this job type */
  data: Option[Any]
) extends ApiModel


