/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Body25 (
  /* The ID of user to add into the channel */
  userId: String,
  /* The ID of root post where link to add channel member originates */
  postRootId: Option[String]
) extends ApiModel


