/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ClusterInfo (
  /* The unique ID for the node */
  id: Option[String],
  /* The server version the node is on */
  version: Option[String],
  /* The hash of the configuartion file the node is using */
  configHash: Option[String],
  /* The URL used to communicate with those node from other nodes */
  internodeUrl: Option[String],
  /* The hostname for this node */
  hostname: Option[String],
  /* The time of the last ping to this node */
  lastPing: Option[Int],
  /* Whether or not the node is alive and well */
  isAlive: Option[Boolean]
) extends ApiModel


