/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class CommandResponse (
  /* The response type either in_channel or ephemeral */
  responseType: Option[String],
  text: Option[String],
  username: Option[String],
  iconURL: Option[String],
  gotoLocation: Option[String],
  attachments: Option[Seq[SlackAttachment]]
) extends ApiModel


