/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Command (
  /* The ID of the slash command */
  id: Option[String],
  /* The token which is used to verify the source of the payload */
  token: Option[String],
  /* Timestamp when the command was created */
  createAt: Option[Int],
  /* Timestamp when the command was last updated */
  updatedAt: Option[Int],
  /* Timestamp when the command was deleted, 0 if never deleted */
  deletedAt: Option[Int],
  /* The user id for the commands creator */
  creatorId: Option[String],
  /* The team id for which this command is configured */
  teamId: Option[String],
  /* The string that triggers this command */
  trigger: Option[String],
  /* Is the trigger done with HTTP Get ('G') or HTTP Post ('P') */
  method: Option[String],
  /* What is the username for the response post */
  username: Option[String],
  /* The url to find the icon for this users avatar */
  iconUrl: Option[String],
  /* Use auto complete for this command */
  autoComplete: Option[Boolean],
  /* The description for this command shown when selecting the command */
  autoCompleteDesc: Option[String],
  /* The hint for this command */
  autoCompleteHint: Option[String],
  /* Display name for the command */
  displayName: Option[String],
  /* Description for this command */
  description: Option[String],
  /* The URL that is triggered */
  url: Option[String]
) extends ApiModel


