/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigServiceSettings (
  siteURL: Option[String],
  listenAddress: Option[String],
  connectionSecurity: Option[String],
  tLSCertFile: Option[String],
  tLSKeyFile: Option[String],
  useLetsEncrypt: Option[Boolean],
  letsEncryptCertificateCacheFile: Option[String],
  forward80To443: Option[Boolean],
  readTimeout: Option[Int],
  writeTimeout: Option[Int],
  maximumLoginAttempts: Option[Int],
  segmentDeveloperKey: Option[String],
  googleDeveloperKey: Option[String],
  enableOAuthServiceProvider: Option[Boolean],
  enableIncomingWebhooks: Option[Boolean],
  enableOutgoingWebhooks: Option[Boolean],
  enableCommands: Option[Boolean],
  enableOnlyAdminIntegrations: Option[Boolean],
  enablePostUsernameOverride: Option[Boolean],
  enablePostIconOverride: Option[Boolean],
  enableTesting: Option[Boolean],
  enableDeveloper: Option[Boolean],
  enableSecurityFixAlert: Option[Boolean],
  enableInsecureOutgoingConnections: Option[Boolean],
  enableMultifactorAuthentication: Option[Boolean],
  enforceMultifactorAuthentication: Option[Boolean],
  allowCorsFrom: Option[String],
  sessionLengthWebInDays: Option[Int],
  sessionLengthMobileInDays: Option[Int],
  sessionLengthSSOInDays: Option[Int],
  sessionCacheInMinutes: Option[Int],
  websocketSecurePort: Option[Int],
  websocketPort: Option[Int],
  webserverMode: Option[String],
  enableCustomEmoji: Option[Boolean],
  restrictCustomEmojiCreation: Option[String]
) extends ApiModel


