/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigEmailSettings (
  enableSignUpWithEmail: Option[Boolean],
  enableSignInWithEmail: Option[Boolean],
  enableSignInWithUsername: Option[Boolean],
  sendEmailNotifications: Option[Boolean],
  requireEmailVerification: Option[Boolean],
  feedbackName: Option[String],
  feedbackEmail: Option[String],
  feedbackOrganization: Option[String],
  sMTPUsername: Option[String],
  sMTPPassword: Option[String],
  sMTPServer: Option[String],
  sMTPPort: Option[String],
  connectionSecurity: Option[String],
  inviteSalt: Option[String],
  passwordResetSalt: Option[String],
  sendPushNotifications: Option[Boolean],
  pushNotificationServer: Option[String],
  pushNotificationContents: Option[String],
  enableEmailBatching: Option[Boolean],
  emailBatchingBufferSize: Option[Int],
  emailBatchingInterval: Option[Int]
) extends ApiModel


