/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigFileSettings (
  maxFileSize: Option[Int],
  driverName: Option[String],
  directory: Option[String],
  enablePublicLink: Option[Boolean],
  publicLinkSalt: Option[String],
  thumbnailWidth: Option[Int],
  thumbnailHeight: Option[Int],
  previewWidth: Option[Int],
  previewHeight: Option[Int],
  profileWidth: Option[Int],
  profileHeight: Option[Int],
  initialFont: Option[String],
  amazonS3AccessKeyId: Option[String],
  amazonS3SecretAccessKey: Option[String],
  amazonS3Bucket: Option[String],
  amazonS3Region: Option[String],
  amazonS3Endpoint: Option[String],
  amazonS3SSL: Option[Boolean]
) extends ApiModel


