/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Config (
  serviceSettings: Option[ConfigServiceSettings],
  teamSettings: Option[ConfigTeamSettings],
  sqlSettings: Option[ConfigSqlSettings],
  logSettings: Option[ConfigLogSettings],
  passwordSettings: Option[ConfigPasswordSettings],
  fileSettings: Option[ConfigFileSettings],
  emailSettings: Option[ConfigEmailSettings],
  rateLimitSettings: Option[ConfigRateLimitSettings],
  privacySettings: Option[ConfigPrivacySettings],
  supportSettings: Option[ConfigSupportSettings],
  gitLabSettings: Option[ConfigGitLabSettings],
  googleSettings: Option[ConfigGitLabSettings],
  office365Settings: Option[ConfigGitLabSettings],
  ldapSettings: Option[ConfigLdapSettings],
  complianceSettings: Option[ConfigComplianceSettings],
  localizationSettings: Option[ConfigLocalizationSettings],
  samlSettings: Option[ConfigSamlSettings],
  nativeAppSettings: Option[ConfigNativeAppSettings],
  clusterSettings: Option[ConfigClusterSettings],
  metricsSettings: Option[ConfigMetricsSettings],
  analyticsSettings: Option[ConfigAnalyticsSettings],
  webrtcSettings: Option[ConfigWebrtcSettings]
) extends ApiModel


