/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigLdapSettings (
  enable: Option[Boolean],
  ldapServer: Option[String],
  ldapPort: Option[Int],
  connectionSecurity: Option[String],
  baseDN: Option[String],
  bindUsername: Option[String],
  bindPassword: Option[String],
  userFilter: Option[String],
  firstNameAttribute: Option[String],
  lastNameAttribute: Option[String],
  emailAttribute: Option[String],
  usernameAttribute: Option[String],
  nicknameAttribute: Option[String],
  idAttribute: Option[String],
  positionAttribute: Option[String],
  syncIntervalMinutes: Option[Int],
  skipCertificateVerification: Option[Boolean],
  queryTimeout: Option[Int],
  maxPageSize: Option[Int],
  loginFieldName: Option[String]
) extends ApiModel


