/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigSqlSettings (
  driverName: Option[String],
  dataSource: Option[String],
  dataSourceReplicas: Option[Seq[String]],
  maxIdleConns: Option[Int],
  maxOpenConns: Option[Int],
  trace: Option[Boolean],
  atRestEncryptKey: Option[String]
) extends ApiModel


