/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigTeamSettings (
  siteName: Option[String],
  maxUsersPerTeam: Option[Int],
  enableTeamCreation: Option[Boolean],
  enableUserCreation: Option[Boolean],
  enableOpenServer: Option[Boolean],
  restrictCreationToDomains: Option[String],
  enableCustomBrand: Option[Boolean],
  customBrandText: Option[String],
  customDescriptionText: Option[String],
  restrictDirectMessage: Option[String],
  restrictTeamInvite: Option[String],
  restrictPublicChannelManagement: Option[String],
  restrictPrivateChannelManagement: Option[String],
  restrictPublicChannelCreation: Option[String],
  restrictPrivateChannelCreation: Option[String],
  restrictPublicChannelDeletion: Option[String],
  restrictPrivateChannelDeletion: Option[String],
  userStatusAwayTimeout: Option[Int],
  maxChannelsPerTeam: Option[Int],
  maxNotificationsPerChannel: Option[Int]
) extends ApiModel


