/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigGitLabSettings (
  enable: Option[Boolean],
  secret: Option[String],
  id: Option[String],
  scope: Option[String],
  authEndpoint: Option[String],
  tokenEndpoint: Option[String],
  userApiEndpoint: Option[String]
) extends ApiModel


