/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigWebrtcSettings (
  enable: Option[Boolean],
  gatewayWebsocketUrl: Option[String],
  gatewayAdminUrl: Option[String],
  gatewayAdminSecret: Option[String],
  stunURI: Option[String],
  turnURI: Option[String],
  turnUsername: Option[String],
  turnSharedKey: Option[String]
) extends ApiModel


