/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class ConfigLogSettings (
  enableConsole: Option[Boolean],
  consoleLevel: Option[String],
  enableFile: Option[Boolean],
  fileLevel: Option[String],
  fileFormat: Option[String],
  fileLocation: Option[String],
  enableWebhookDebugging: Option[Boolean],
  enableDiagnostics: Option[Boolean]
) extends ApiModel


