/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class DataRetentionPolicy (
  /* Indicates whether data retention policy deletion of messages is enabled. */
  messageDeletionEnabled: Option[Boolean],
  /* Indicates whether data retention policy deletion of file attachments is enabled. */
  fileDeletionEnabled: Option[Boolean],
  /* The current server timestamp before which messages should be deleted. */
  messageRetentionCutoff: Option[Int],
  /* The current server timestamp before which files should be deleted. */
  fileRetentionCutoff: Option[Int]
) extends ApiModel


