/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Emoji (
  /* The ID of the emoji */
  id: Option[String],
  /* The ID of the user that made the emoji */
  creatorId: Option[String],
  /* The name of the emoji */
  name: Option[String],
  /* The time at which the emoji was made */
  createAt: Option[Int],
  /* The time at which the emoji was updated. */
  updateAt: Option[Int],
  /* The time at which the emoji was deleted. */
  deleteAt: Option[Int]
) extends ApiModel


