/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class IncomingWebhook (
  /* The unique identifier for this incoming webhook */
  id: Option[String],
  createAt: Option[Int],
  updateAt: Option[Int],
  deleteAt: Option[Int],
  /* The ID of a public channel or private group that receives the webhook payloads */
  channelId: Option[String],
  /* The description for this incoming webhook */
  description: Option[String],
  /* The display name for this incoming webhook */
  displayName: Option[String]
) extends ApiModel


