/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class InlineResponse2006 (
  /* A list of file metadata that has been stored in the database */
  fileInfos: Option[Seq[FileInfo]],
  /* A list of the client_ids that were provided in the request */
  clientIds: Option[Seq[String]]
) extends ApiModel


