/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class InlineResponse2007 (
  /* The WebRTC token */
  token: Option[String],
  /* The URL to the gateway server */
  gatewayUrl: Option[String],
  /* The URI to the STUN server */
  stunUri: Option[String],
  /* The URI to the TURN server */
  turnUri: Option[String],
  /* The password to use with the TURN server */
  turnPassword: Option[String],
  /* The username to use with the TURN server */
  turnUsername: Option[String]
) extends ApiModel


