/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class InlineResponse200 (
  /* The MFA secret as a string */
  secret: Option[String],
  /* A base64 encoded QR code image */
  qrCode: Option[String]
) extends ApiModel


