/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class InlineResponse2002 (
  /* The link for the user to follow to login or to complete the account switching when the current service is OAuth2/SAML */
  followLink: Option[String]
) extends ApiModel


