/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class InlineResponse2005 (
  /* Value should be \"OK\" if successful */
  status: Option[String],
  /* A JSON object mapping channel IDs to the channel view times */
  lastViewedAtTimes: Option[Any]
) extends ApiModel


