/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class OAuthApp (
  /* The client id of the application */
  id: Option[String],
  /* The client secret of the application */
  clientSecret: Option[String],
  /* The name of the client application */
  name: Option[String],
  /* A short description of the application */
  description: Option[String],
  /* A URL to an icon to display with the application */
  iconUrl: Option[String],
  /* A list of callback URLs for the appliation */
  callbackUrls: Option[Seq[String]],
  /* A link to the website of the application */
  homepage: Option[String],
  /* Set this to `true` to skip asking users for permission */
  isTrusted: Option[Boolean],
  /* The time of registration for the application */
  createAt: Option[Int],
  /* The last time of update for the application */
  updateAt: Option[Int]
) extends ApiModel


