/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class OpenGraphBook (
  isbn: Option[String],
  releaseDate: Option[String],
  tags: Option[Seq[String]],
  authors: Option[Seq[OpenGraphArticleAuthors]]
) extends ApiModel


