/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class OpenGraph (
  `type`: Option[String],
  url: Option[String],
  title: Option[String],
  description: Option[String],
  determiner: Option[String],
  siteName: Option[String],
  locale: Option[String],
  localesAlternate: Option[Seq[String]],
  images: Option[Seq[OpenGraphImages]],
  videos: Option[Seq[OpenGraphVideos]],
  audios: Option[Seq[OpenGraphAudios]],
  article: Option[OpenGraphArticle],
  book: Option[OpenGraphBook],
  profile: Option[OpenGraphArticleAuthors]
) extends ApiModel


