/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class PluginManifest (
  /* Globally unique identifier that represents the plugin. */
  id: Option[String],
  /* Name of the plugin. */
  name: Option[String],
  /* Description of what the plugin is and does. */
  description: Option[String],
  /* Version number of the plugin. */
  version: Option[String],
  backend: Option[PluginManifestBackend],
  webapp: Option[PluginManifestWebapp],
  /* Settings schema used to define the System Console UI for the plugin. */
  settingsSchema: Option[Any]
) extends ApiModel


