/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Post (
  /* The channel ID to post in */
  channelId: String,
  /* The message contents, can be formatted with Markdown */
  message: String,
  /* The post ID to comment on */
  rootId: Option[String],
  /* A list of file IDs to associate with the post */
  fileIds: Option[Seq[String]],
  /* A general JSON property bag to attach to the post */
  props: Option[String]
) extends ApiModel


