/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Preference (
  /* The ID of the user that owns this preference */
  userId: Option[String],
  category: Option[String],
  name: Option[String],
  value: Option[String]
) extends ApiModel


