/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Session (
  createAt: Option[Int],
  deviceId: Option[String],
  expiresAt: Option[Int],
  id: Option[String],
  isOauth: Option[Boolean],
  lastActivityAt: Option[Int],
  props: Option[Any],
  roles: Option[String],
  teamMembers: Option[Seq[TeamMember]],
  token: Option[String],
  userId: Option[String]
) extends ApiModel


