/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class SlackAttachmentField (
  title: Option[String],
  /* The value of the attachment, set as string but capable with golang interface */
  value: Option[String],
  short: Option[Boolean]
) extends ApiModel


