/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class SlackAttachment (
  id: Option[String],
  fallback: Option[String],
  color: Option[String],
  pretext: Option[String],
  authorName: Option[String],
  authorLink: Option[String],
  authorIcon: Option[String],
  title: Option[String],
  titleLink: Option[String],
  text: Option[String],
  fields: Option[Seq[SlackAttachmentField]],
  imageURL: Option[String],
  thumbURL: Option[String],
  footer: Option[String],
  footerIcon: Option[String],
  /* The timestamp of the slack attahment, either type of string or integer */
  timestamp: Option[String]
) extends ApiModel


