/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class Team (
  id: Option[String],
  createAt: Option[Int],
  updateAt: Option[Int],
  deleteAt: Option[Int],
  displayName: Option[String],
  name: Option[String],
  description: Option[String],
  email: Option[String],
  `type`: Option[String],
  allowedDomains: Option[String],
  inviteId: Option[String],
  allowOpenInvite: Option[Boolean]
) extends ApiModel


