/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class User (
  id: Option[String],
  createAt: Option[Int],
  updateAt: Option[Int],
  deleteAt: Option[Int],
  username: Option[String],
  firstName: Option[String],
  lastName: Option[String],
  nickname: Option[String],
  email: Option[String],
  emailVerified: Option[Boolean],
  authService: Option[String],
  roles: Option[String],
  locale: Option[String],
  /* Field only visible to self and admins */
  notifyProps: Option[UserNotifyProps],
  props: Option[Any],
  lastPasswordUpdate: Option[Int],
  lastPictureUpdate: Option[Int],
  failedAttempts: Option[Int],
  mfaActive: Option[Boolean]
) extends ApiModel


