/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class UserAutocompleteInChannel (
  /* A list of user objects in the channel */
  inChannel: Option[Seq[User]],
  /* A list of user objects not in the channel */
  outOfChannel: Option[Seq[User]]
) extends ApiModel


