/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class UserNotifyProps (
  /* Set to \"true\" to enable email notifications, \"false\" to disable. Defaults to \"true\". */
  email: Option[String],
  /* Set to \"all\" to receive push notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"mention\". */
  push: Option[String],
  /* Set to \"all\" to receive desktop notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"all\". */
  desktop: Option[String],
  /* Set to \"true\" to enable sound on desktop notifications, \"false\" to disable. Defaults to \"true\". */
  desktopSound: Option[String],
  /* A comma-separated list of words to count as mentions. Defaults to username and @username. */
  mentionKeys: Option[String],
  /* Set to \"true\" to enable channel-wide notifications (@channel, @all, etc.), \"false\" to disable. Defaults to \"true\". */
  channel: Option[String],
  /* Set to \"true\" to enable mentions for first name. Defaults to \"true\" if a first name is set, \"false\" otherwise. */
  firstName: Option[String]
) extends ApiModel


