/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class UserAccessToken (
  /* Unique identifier for the token */
  id: Option[String],
  /* The token used for authentication */
  token: Option[String],
  /* The user the token authenticates for */
  userId: Option[String],
  /* A description of the token usage */
  description: Option[String]
) extends ApiModel


