/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package mattermost.api.client.model

import mattermost.api.client.core.ApiModel

case class UserAutocomplete (
  /* A list of users that are the main result of the query */
  users: Option[Seq[User]],
  /* A special case list of users returned when autocompleting in a specific channel. Omitted when empty or not relevant */
  outOfChannel: Option[Seq[User]]
) extends ApiModel


